### ISSUE TITLE
List dependencies needed to run/test application

### ISSUE THREAD

**Issue by james2432** [plepe/openstreetmap-date-format#1]
Needs:
1. Mochajs

To run tests

1. Standard

to run lint

**Comment by plepe** [comment]
If you run `npm install`, as shown in the HOWTO, npm should install all necessary dependencies.

**Comment by james2432** [comment]
npm install only installed ordinal and moment, but did not install the required frameworks for running:
npm run test
npm run lint

**Comment by plepe** [comment]
Apparently your npm is in production mode, because my npm installed all dependencies and devDependencies.

From https://docs.npmjs.com/cli/install:
> By default, npm install will install all modules listed as dependencies in package.json . With the --production flag (or when the NODE_ENV environment variable is set to production ), npm will not install modules listed in devDependencies .

I updated the howto to handle these cases: b62c19532feaf1aa759cadfadb9a5974fe68343f
