### ISSUE TITLE
Re-license with MIT license

### ISSUE THREAD

**Issue by plepe** [plepe/openstreetmap-date-format#3]
Hi!

I re-licensed the code today with a MIT license instead of the original GPL-3.0. But then I noticed, that you, @james2432, also contributed to the repository. Are you in favor of this change? If not, please reply soon, I would need to remove your source code from the archive.

Sorry for not asking you first ...

**Comment by james2432** [comment]
what was the license before(just curious)?

I don't mind the MIT license, it's pretty open

**Comment by plepe** [comment]
Thanks for your reply!

It was GPL-3.0. But that's a problem for non-GPL projects, because that would force them to change to GPL too ...
